spring:
  application:
    name: resource-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        fail-fast: false
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        fail-fast: false
        file-extension: yaml
        import-check:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/web3_resource?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8089
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
resource:
  upload-dir: runtime/uploads
logging:
  level:
    com.web3.resource: debug
