spring:
  application:
    name: blog-service
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        file-extension: yaml
        import-check:
          enabled: false
  config:
    import: optional:nacos:${spring.application.name}.yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/web3_blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

server:
  port: 8082

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.web3.blog: debug
