spring:
  application:
    name: jarvis-service
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        file-extension: yaml
        import-check:
          enabled: false
  config:
    import: optional:nacos:${spring.application.name}.yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/web3_jarvis?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: 6379
      password: ${REDIS_PASSWORD:}

  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /

server:
  port: 9001

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.web3.jarvis: debug
